env:
  start: [0.0, 7.0, 0.0, 2.0] # px, py, phi, vx, vy, phi_dot
  goal_state: [4.0, 1.0]
  terminate_state: [0.0, 0.0] # px, py, phi, vx, vy, phi_dot
  dynamics: 'car_racing' # "pendulum"
  prior_dyn_meas: True 
  train_data_has_derivatives: False
  n_data_x: 2
  n_data_u: 2
  params:
    lf: 1.105 #0.55 #1.105, 0.275
    lr: 1.738 #0.85 #1.738, 0.425
    c: 0.025
  track:
    P1: [[1.0, 0.0],[0.0, 9.0]]
    d1: 1600.0
    P2: [[1.0, 0.0],[0.0, 45.0]]
    d2: 400.0
    Pc: [[1.0, 0.0],[0.0, 20.0]]
    dc: 900.0
  ellipses:

agent:
  g_dim :
    ny : 4
    nx : 4
    nu : 2
  dim :
    ny : 4
    nx : 4
    nu : 2
  Dyn_gp_lengthscale :
      y1 : [5.2649, 4.5967, 7.0177] # y1 : [5.2649, 4.5967, 7.0177] #[2.6384, 2.5857, 2.5669]
      y2 : [3.9696, 2.1265, 6.6749] # y2 : [3.9696, 2.1265, 6.6749] #[2.1422, 2.7733, 2.1221]
      both : [[[5.2649, 4.5967, 7.0177]], [[3.9696, 2.1265, 6.6749]] ]
  Dyn_gp_noise : 1.0e-6
  Dyn_gp_outputscale : 
    y1 : 0.1040 #0.3040 #0.75  #0.65
    y2 : 0.1071 #0.3071 #0.65 #0.455, noise multiplier 3.0e-7 results in smooth trajectories
    both : [0.65, 0.55] #[65,55] #[0.65, 0.55]
  Dyn_gp_task_noises : 
    val : [3.8, 1.27, 3.8, 1.27]
    multiplier : 1.0e-5                     #1.0e-5 Low noise value make it crazy fast
  Dyn_gp_beta : 3.5 # 1.5
  mean_shift_val : 2
  cov_module: 'Matern'     #'Matern', Sq_exp
  num_dyn_samples: 15 
  mean_as_dyn_sample: False
  true_dyn_as_sample: False        # This is for debugging, set num_dyn_samples to 1
  Dyn_gp_jitter: 1.0e-6
  Dyn_gp_variance_is_zero: 1.1e-6
  Dyn_gp_min_data_dist: 1.0e-4
  tight:
    use: False
    dyn_eps: 0.001
    Lipschitz: 1.015
    w_bound: 0.007
  shift_soln: False
  load_training_data: False
  run:
    optimistic: False
    pessimistic: True
    true_param_as_sample: True # Debug mode
    variance_cost: False
  BLR:
    lambda_reg: 1.0e-6
    noise_var: 5.0e-4

visu:
  show: True
  traj_file_name: "data_lap1.pkl"
  training_data_file_name: "training_data_lap1.pkl"

common:
  use_cuda : False
  use_BLR : True
  active_learning:
    use: True
    frequency: 1
  num_MPC_itrs : 500
  dynamics_rejection: False

optimizer:
  H : 30 # horizon
  u_min : [-0.6, -2] # Minimum control input
  u_max : [0.6, 20]        
  data_u_min : [-0.01, -0.1] # Minimum control input
  data_u_max : [0.01, 2.0]           
  # u_min : [-30, -30] # Minimum control input
  # u_max : [30, 30] 
  # x_min : [-45.0, -15.0, -40.14, -15] # Minimum state value
  # x_max : [ 45.0, 15.0, 40.14, 20] # x,y,v,theta,theta_dot
  x_min : [-45.0, -15.0, -40.14, -15] # Minimum state value
  x_max : [ 45.0, 15.0, 40.14, 20] # x,y,v,theta,theta_dot
  data_x_min : [-1.0, 5.2, -0.2, -1.0] # Minimum state value
  data_x_max : [ 1.0, 7.6, 0.2, 10.0] # x,y,v,theta,theta_dot
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 1
    tol_nlp: 1.0e-4 
  order: 2
  x_dim: 2
  dt: 0.06 # 0.010
  w: 50
  Qx: [1.0, 1.0] # [1.0, 1.0, 1.0, 1.0]  
  Qu: [0.1, 0.01]
  cost: "expected" 
  options: {
    levenberg_marquardt: 0.33
  }
  terminal_tightening:
    x_tight: [0.1, 0.1]
    u_tight: [0.1]
    # P:  [[2.48651083, 1.48325991],[1.48325991, 2.65037241]]
    P:  [[1.0, 0.0],[0.0, 1.0]]
    delta: 1.0


optimistic_optimizer:
  H : 30 # horizon
  u_min : [-5, -5, -0.3, -0.3, -0.3,-0.3, -0.3, -0.3] # Minimum control input
  u_max : [5, 5, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]          
  x_min : [-5, -5, -3.1417, -2, -2, -1] # Minimum state value
  x_max : [ 5, 5, 3.1417, 2, 2, 1] # x,y,v,theta,theta_dot
  linear_solver : 'ma57' #
  oracle:
    max_sqp_iter: 10
    tol_nlp: 1.0e-6
  SEMPC:
    max_sqp_iter: 1
    tol_nlp: 1.0e-4 
  order: 2
  x_dim: 2
  # dt: 0.1 # 0.010
  w: 50
  Qx: [5, 5] # [1.0, 1.0, 1.0, 1.0]  
  Qu: [1, 1, 1, 1, 1, 1,1, 1]
  cost: "expected" 
  options: {
    levenberg_marquardt: 10.0
  }
  terminal_tightening:
    x_tight: [0.1, 0.1]
    u_tight: [0.1]
    P:  [[2.48651083, 1.48325991],[1.48325991, 2.65037241]]
    delta: 1.0

experiment:
  name: "DEMPC" #
  generate_regret_plot : True
  folder: "car"
  rnd_seed: 
    use: False
    value: 123456